import React from 'react';
import Modal from '../common/Modal';
import { PlayCircle, ShieldCheck, AlertTriangle } from 'lucide-react';

const TrainingConfirmModal = ({ isOpen, onClose, onConfirm, recommendation, datasetName, hardwareInfo }) => {
  if (!recommendation) return null;

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Confirm Module 7 Local Training Launch" maxWidth="560px">
      <div>
        <p style={{ fontSize: '12px', color: 'var(--text-secondary)', marginBottom: '16px' }}>
          Please review the resource-aware execution parameters generated by <strong>Module 8</strong>. 
          Once launched, <strong>Module 7</strong> will execute local deep learning training strictly within the hospital node.
        </p>

        {/* Selected Config Summary */}
        <div style={{
          backgroundColor: '#0a101d',
          border: '1px solid var(--border-subtle)',
          borderRadius: 'var(--radius-lg)',
          padding: '14px',
          marginBottom: '16px'
        }}>
          <div style={{ fontSize: '11px', textTransform: 'uppercase', color: 'var(--text-muted)', fontWeight: 600, marginBottom: '10px' }}>
            Target Training Parameters
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '10px', fontSize: '12px' }}>
            <div>
              <span className="text-muted">Target Dataset:</span>
              <div style={{ fontWeight: 600, color: 'var(--text-primary)' }}>{datasetName || 'Pediatric Chest X-Ray Cohort'}</div>
            </div>
            <div>
              <span className="text-muted">Model Architecture:</span>
              <div style={{ fontWeight: 600, color: 'var(--accent-teal)' }}>{recommendation.model_name} ({recommendation.architecture})</div>
            </div>
            <div>
              <span className="text-muted">Compute Device:</span>
              <div className="font-mono text-primary" style={{ fontWeight: 600 }}>{recommendation.device}</div>
            </div>
            <div>
              <span className="text-muted">Tensor Precision:</span>
              <div className="font-mono text-cyan" style={{ fontWeight: 600 }}>{recommendation.precision}</div>
            </div>
            <div>
              <span className="text-muted">Batch Size:</span>
              <div className="font-mono text-primary" style={{ fontWeight: 600 }}>{recommendation.batch_size}</div>
            </div>
            <div>
              <span className="text-muted">Target Epochs:</span>
              <div className="font-mono text-primary" style={{ fontWeight: 600 }}>{recommendation.epochs}</div>
            </div>
            <div>
              <span className="text-muted">DataLoader Workers:</span>
              <div className="font-mono text-primary">{recommendation.workers}</div>
            </div>
            <div>
              <span className="text-muted">Estimated Duration:</span>
              <div className="font-mono text-emerald" style={{ fontWeight: 600 }}>{recommendation.estimated_time_range}</div>
            </div>
          </div>
        </div>

        {/* Hardware & Privacy Assurances */}
        <div style={{
          padding: '10px 12px',
          backgroundColor: 'rgba(16, 185, 129, 0.08)',
          border: '1px solid rgba(16, 185, 129, 0.25)',
          borderRadius: 'var(--radius-md)',
          marginBottom: '20px',
          fontSize: '11px',
          display: 'flex',
          alignItems: 'center',
          gap: '8px'
        }}>
          <ShieldCheck size={16} color="var(--status-healthy)" />
          <span style={{ color: 'var(--text-secondary)' }}>
            <strong>Zero Egress Guarantee:</strong> PyTorch training executes on local CUDA streams. No raw clinical images or patient metadata will be transmitted outside this hospital node.
          </span>
        </div>

        {/* Actions */}
        <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '10px' }}>
          <button onClick={onClose} className="btn btn-secondary">
            Cancel
          </button>
          <button onClick={onConfirm} className="btn btn-teal">
            <PlayCircle size={14} /> Start Training
          </button>
        </div>
      </div>
    </Modal>
  );
};

export default TrainingConfirmModal;
