/**
 * federation.test.js — Backend API tests for M9 Federation endpoints.
 *
 * Approach:
 *   - Mock the User model so authMiddleware can find users per role without DB
 *   - Mock child_process.spawn so no Python is invoked
 *   - No MongoMemoryServer needed
 *
 * Covers:
 *   1. Hospital identity mapping — req.user.hospital_id (not user_id) reaches M9
 *   2. Hospital A cannot see Hospital B's federation status
 *   3. Role-based access on all 9 /api/v1/federation/* endpoints
 *   4. JWT authentication (expired, malformed, missing)
 *   5. Server-side enforcement — middleware rejects before Python is called
 */

const request = require('supertest');
const jwt = require('jsonwebtoken');

// ── Env setup (before any require of app modules) ────────────────────────────
const JWT_SECRET = 'federation-test-jwt-secret';
process.env.JWT_SECRET = JWT_SECRET;
process.env.JWT_EXPIRES_IN = '1h';
process.env.NODE_ENV = 'test';
process.env.MONGODB_URI = 'mongodb://localhost:27017/test-noop';

// ── User database: two distinct hospitals, one researcher, one admin ──────────
//
//   user_id       role                hospital_id   (invariant: DIFFERENT fields)
//   ─────────────────────────────────────────────────────────────────────────────
//   USR_hospa001  hospital_operator   HOSP-ALPHA    (registered as Hospital Alpha)
//   USR_hospb002  hospital_operator   HOSP-BETA     (registered as Hospital Beta)
//   USR_res0001   researcher          null
//   USR_adm0001   admin               null
//
// This matches the M1-M3 schema:
//   - user_id   = generated by generateUserId() → "USR_<random hex>"
//   - hospital_id = supplied at registration from req.body.hospital_id,
//                   verified against Hospital collection

const MOCK_USERS = {
  'USR_hospa001': {
    user_id: 'USR_hospa001',
    name: 'Alpha Hospital Op',
    email: 'alpha@hospital.com',
    role: 'hospital_operator',
    status: 'active',
    hospital_id: 'HOSP-ALPHA',   // ← authoritative M1/M3 hospital identifier
  },
  'USR_hospb002': {
    user_id: 'USR_hospb002',
    name: 'Beta Hospital Op',
    email: 'beta@hospital.com',
    role: 'hospital_operator',
    status: 'active',
    hospital_id: 'HOSP-BETA',
  },
  'USR_res0001': {
    user_id: 'USR_res0001',
    name: 'Test Researcher',
    email: 'researcher@test.com',
    role: 'researcher',
    status: 'active',
    hospital_id: null,
  },
  'USR_adm0001': {
    user_id: 'USR_adm0001',
    name: 'Test Admin',
    email: 'admin@test.com',
    role: 'admin',
    status: 'active',
    hospital_id: null,
  },
};

// ── Mock the User model ───────────────────────────────────────────────────────
jest.mock('../../src/authentication/models/User', () => {
  const MOCK_USERS = {
    'USR_hospa001': { user_id: 'USR_hospa001', name: 'Alpha Hospital Op', email: 'alpha@hospital.com', role: 'hospital_operator', status: 'active', hospital_id: 'HOSP-ALPHA' },
    'USR_hospb002': { user_id: 'USR_hospb002', name: 'Beta Hospital Op', email: 'beta@hospital.com', role: 'hospital_operator', status: 'active', hospital_id: 'HOSP-BETA' },
    'USR_res0001':  { user_id: 'USR_res0001', name: 'Test Researcher', email: 'researcher@test.com', role: 'researcher', status: 'active', hospital_id: null },
    'USR_adm0001':  { user_id: 'USR_adm0001', name: 'Test Admin', email: 'admin@test.com', role: 'admin', status: 'active', hospital_id: null },
  };

  return {
    findOne: jest.fn(({ user_id }) => Promise.resolve(MOCK_USERS[user_id] || null)),
    find: jest.fn().mockResolvedValue([]),
    create: jest.fn().mockResolvedValue({}),
    deleteMany: jest.fn().mockResolvedValue({}),
  };
});

// ── Mock Hospital model ───────────────────────────────────────────────────────
jest.mock('../../src/authentication/models/Hospital', () => ({
  findOne: jest.fn().mockResolvedValue(null),
  find: jest.fn().mockResolvedValue([]),
  create: jest.fn().mockResolvedValue({}),
  deleteMany: jest.fn().mockResolvedValue({}),
}));

// ── Mock AuditLog and AuditService ───────────────────────────────────────────
jest.mock('../../src/authentication/models/AuditLog', () => ({
  create: jest.fn().mockResolvedValue({}),
  find: jest.fn().mockResolvedValue([]),
  deleteMany: jest.fn().mockResolvedValue({}),
}));

jest.mock('../../src/authentication/services/auditService', () => ({
  logEvent: jest.fn().mockResolvedValue({}),
}));

// ── Mock TrainingRequest model ────────────────────────────────────────────────
jest.mock('../../src/models/TrainingRequest', () => ({
  find: jest.fn().mockResolvedValue([]),
  findOne: jest.fn().mockResolvedValue(null),
  create: jest.fn().mockResolvedValue({}),
  deleteMany: jest.fn().mockResolvedValue({}),
}));

// ── Mock Notification model (Module 18) ──────────────────────────────────────
jest.mock('../../src/models/Notification', () => ({
  insertMany: jest.fn(async (docs) => docs.map((d) => ({ ...d, toObject: () => d }))),
  find: jest.fn(),
  updateMany: jest.fn().mockResolvedValue({}),
}));

// ── Mock DB connection ────────────────────────────────────────────────────────
jest.mock('../../src/database/connection/db', () => jest.fn().mockResolvedValue(true));

// ── Mock child_process.spawn — track what hospital_id Python receives ─────────
let lastSpawnPayload = null;

jest.mock('child_process', () => {
  const { EventEmitter } = require('events');
  const { Readable } = require('stream');

  return {
    spawn: jest.fn(() => {
      const child = new EventEmitter();
      child.stdout = new Readable({ read() {} });
      child.stderr = new Readable({ read() {} });
      child.stdin = {
        write: jest.fn((data) => {
          try { lastSpawnPayload = JSON.parse(data); } catch (_) {}
        }),
        end: jest.fn(),
      };
      setImmediate(() => {
        child.stdout.push(JSON.stringify({ success: true, jobs: [], models: [], updates: [] }));
        child.stdout.push(null);
        child.emit('close', 0);
      });
      return child;
    }),
  };
});

// ── Load app AFTER all mocks ─────────────────────────────────────────────────
const app = require('../../src/app');

// ── Token helpers — JWT payload mirrors authService.generateToken() ───────────
const makeToken = (user) =>
  jwt.sign(
    {
      sub: user.user_id,
      user_id: user.user_id,
      role: user.role,
      hospital_id: user.hospital_id || null,
    },
    JWT_SECRET,
    { expiresIn: '1h' }
  );

const HOSP_ALPHA = () => makeToken(MOCK_USERS['USR_hospa001']);
const HOSP_BETA  = () => makeToken(MOCK_USERS['USR_hospb002']);
const RESEARCHER = () => makeToken(MOCK_USERS['USR_res0001']);
const ADMIN      = () => makeToken(MOCK_USERS['USR_adm0001']);

beforeEach(() => {
  lastSpawnPayload = null;
  jest.clearAllMocks();
  // Re-arm the spawn mock after clearAllMocks
  const { spawn } = require('child_process');
  const { EventEmitter } = require('events');
  const { Readable } = require('stream');
  spawn.mockImplementation(() => {
    const child = new EventEmitter();
    child.stdout = new Readable({ read() {} });
    child.stderr = new Readable({ read() {} });
    child.stdin = {
      write: jest.fn((data) => {
        try { lastSpawnPayload = JSON.parse(data); } catch (_) {}
      }),
      end: jest.fn(),
    };
    setImmediate(() => {
      child.stdout.push(JSON.stringify({ success: true, jobs: [], models: [], updates: [] }));
      child.stdout.push(null);
      child.emit('close', 0);
    });
    return child;
  });
  // Re-arm User.findOne after clearAllMocks
  const User = require('../../src/authentication/models/User');
  const DB = {
    'USR_hospa001': { user_id: 'USR_hospa001', name: 'Alpha Hospital Op', email: 'alpha@hospital.com', role: 'hospital_operator', status: 'active', hospital_id: 'HOSP-ALPHA' },
    'USR_hospb002': { user_id: 'USR_hospb002', name: 'Beta Hospital Op', email: 'beta@hospital.com', role: 'hospital_operator', status: 'active', hospital_id: 'HOSP-BETA' },
    'USR_res0001':  { user_id: 'USR_res0001', name: 'Test Researcher', email: 'researcher@test.com', role: 'researcher', status: 'active', hospital_id: null },
    'USR_adm0001':  { user_id: 'USR_adm0001', name: 'Test Admin', email: 'admin@test.com', role: 'admin', status: 'active', hospital_id: null },
  };
  User.findOne.mockImplementation(({ user_id }) => Promise.resolve(DB[user_id] || null));
});

// ═════════════════════════════════════════════════════════════════════════════
// SECTION 1 — HOSPITAL IDENTITY MAPPING
//
// Verifies:
//   JWT → authMiddleware → req.user (User document from DB)
//   → req.user.hospital_id (NOT req.user.user_id)
//   → M9 participant_id
// ═════════════════════════════════════════════════════════════════════════════

describe('Hospital Identity Mapping — req.user.hospital_id reaches M9', () => {
  test('Hospital Alpha: hospital_id=HOSP-ALPHA is sent to Python adapter (not USR_hospa001)', async () => {
    const res = await request(app)
      .get('/api/v1/federation/hospital-status')
      .set('Authorization', `Bearer ${HOSP_ALPHA()}`);
    expect(res.status).toBe(200);
    // Verify the Python subprocess received the correct hospital_id
    expect(lastSpawnPayload).not.toBeNull();
    expect(lastSpawnPayload.hospital_id).toBe('HOSP-ALPHA');
    // Crucially: must NOT be the user_id
    expect(lastSpawnPayload.hospital_id).not.toBe('USR_hospa001');
  });

  test('Hospital Beta: hospital_id=HOSP-BETA is sent to Python adapter (not USR_hospb002)', async () => {
    const res = await request(app)
      .get('/api/v1/federation/hospital-status')
      .set('Authorization', `Bearer ${HOSP_BETA()}`);
    expect(res.status).toBe(200);
    expect(lastSpawnPayload).not.toBeNull();
    expect(lastSpawnPayload.hospital_id).toBe('HOSP-BETA');
    expect(lastSpawnPayload.hospital_id).not.toBe('USR_hospb002');
  });

  test('Hospital Alpha and Beta receive DIFFERENT hospital_ids — no cross-contamination', async () => {
    const resA = await request(app)
      .get('/api/v1/federation/hospital-status')
      .set('Authorization', `Bearer ${HOSP_ALPHA()}`);
    const payloadA = lastSpawnPayload;
    lastSpawnPayload = null;

    const resB = await request(app)
      .get('/api/v1/federation/hospital-status')
      .set('Authorization', `Bearer ${HOSP_BETA()}`);
    const payloadB = lastSpawnPayload;

    expect(resA.status).toBe(200);
    expect(resB.status).toBe(200);
    expect(payloadA.hospital_id).toBe('HOSP-ALPHA');
    expect(payloadB.hospital_id).toBe('HOSP-BETA');
    expect(payloadA.hospital_id).not.toBe(payloadB.hospital_id);
  });

  test('Admin has null hospital_id — hospital-status returns 400 (not 200)', async () => {
    // Admin has no hospital_id; the controller must reject before calling M9
    const res = await request(app)
      .get('/api/v1/federation/hospital-status')
      .set('Authorization', `Bearer ${ADMIN()}`);
    // Admin is blocked at requireRole (403) before hospital_id check
    expect(res.status).toBe(403);
  });

  test('Researcher has null hospital_id — blocked at role middleware (403)', async () => {
    const res = await request(app)
      .get('/api/v1/federation/hospital-status')
      .set('Authorization', `Bearer ${RESEARCHER()}`);
    expect(res.status).toBe(403);
  });

  test('M9 participant_id is the hospital_id from M1-M3 — NOT the user_id', async () => {
    // This test documents the invariant:
    // The User schema has BOTH user_id (USR_xxxx) and hospital_id (admin-defined)
    // req.user.hospital_id is what reaches M9, which matches FederationParticipant.hospital_identifier
    const res = await request(app)
      .get('/api/v1/federation/hospital-status')
      .set('Authorization', `Bearer ${HOSP_ALPHA()}`);
    expect(res.status).toBe(200);
    // Python subprocess must have been called with hospital_id, not user_id
    expect(lastSpawnPayload.hospital_id).toBe('HOSP-ALPHA');
    expect(lastSpawnPayload).not.toHaveProperty('user_id');
  });
});

// ═════════════════════════════════════════════════════════════════════════════
// SECTION 2 — GET /jobs
// ═════════════════════════════════════════════════════════════════════════════

describe('GET /api/v1/federation/jobs', () => {
  test('Admin → 200 + jobs array', async () => {
    const res = await request(app)
      .get('/api/v1/federation/jobs')
      .set('Authorization', `Bearer ${ADMIN()}`);
    expect(res.status).toBe(200);
    expect(res.body.success).toBe(true);
    expect(Array.isArray(res.body.jobs)).toBe(true);
  });

  test('Unauthenticated → 401', async () => {
    const res = await request(app).get('/api/v1/federation/jobs');
    expect(res.status).toBe(401);
  });

  test('Hospital Alpha → 403 (admin only)', async () => {
    const res = await request(app)
      .get('/api/v1/federation/jobs')
      .set('Authorization', `Bearer ${HOSP_ALPHA()}`);
    expect(res.status).toBe(403);
  });

  test('Hospital Beta → 403 (admin only)', async () => {
    const res = await request(app)
      .get('/api/v1/federation/jobs')
      .set('Authorization', `Bearer ${HOSP_BETA()}`);
    expect(res.status).toBe(403);
  });

  test('Researcher → 403 (admin only)', async () => {
    const res = await request(app)
      .get('/api/v1/federation/jobs')
      .set('Authorization', `Bearer ${RESEARCHER()}`);
    expect(res.status).toBe(403);
  });
});

// ═════════════════════════════════════════════════════════════════════════════
// SECTION 3 — GET /jobs/:job_id
// ═════════════════════════════════════════════════════════════════════════════

describe('GET /api/v1/federation/jobs/:job_id', () => {
  test('Admin → endpoint reachable', async () => {
    const res = await request(app)
      .get('/api/v1/federation/jobs/JOB-001')
      .set('Authorization', `Bearer ${ADMIN()}`);
    expect([200, 500]).toContain(res.status);
  });

  test('Unauthenticated → 401', async () => {
    const res = await request(app).get('/api/v1/federation/jobs/JOB-001');
    expect(res.status).toBe(401);
  });

  test('Hospital → 403', async () => {
    const res = await request(app)
      .get('/api/v1/federation/jobs/JOB-001')
      .set('Authorization', `Bearer ${HOSP_ALPHA()}`);
    expect(res.status).toBe(403);
  });

  test('Researcher → 403', async () => {
    const res = await request(app)
      .get('/api/v1/federation/jobs/JOB-001')
      .set('Authorization', `Bearer ${RESEARCHER()}`);
    expect(res.status).toBe(403);
  });
});

// ═════════════════════════════════════════════════════════════════════════════
// SECTION 4 — POST /jobs
// ═════════════════════════════════════════════════════════════════════════════

describe('POST /api/v1/federation/jobs', () => {
  test('Admin → endpoint reachable', async () => {
    const res = await request(app)
      .post('/api/v1/federation/jobs')
      .set('Authorization', `Bearer ${ADMIN()}`)
      .send({ job_id: 'JOB-001', task: 'Cancer', architecture: 'ResNet50', num_classes: 2 });
    expect([200, 500]).toContain(res.status);
  });

  test('Hospital → 403', async () => {
    const res = await request(app)
      .post('/api/v1/federation/jobs')
      .set('Authorization', `Bearer ${HOSP_ALPHA()}`)
      .send({ job_id: 'JOB-001', task: 'Cancer', architecture: 'ResNet50', num_classes: 2 });
    expect(res.status).toBe(403);
  });

  test('Researcher → 403', async () => {
    const res = await request(app)
      .post('/api/v1/federation/jobs')
      .set('Authorization', `Bearer ${RESEARCHER()}`)
      .send({ job_id: 'JOB-001', task: 'Cancer', architecture: 'ResNet50', num_classes: 2 });
    expect(res.status).toBe(403);
  });
});

// ═════════════════════════════════════════════════════════════════════════════
// SECTION 5 — POST /rounds
// ═════════════════════════════════════════════════════════════════════════════

describe('POST /api/v1/federation/rounds', () => {
  test('Admin → endpoint reachable', async () => {
    const res = await request(app)
      .post('/api/v1/federation/rounds')
      .set('Authorization', `Bearer ${ADMIN()}`)
      .send({ job_id: 'JOB-001', round_id: 'RND-001', round_number: 1 });
    expect([200, 500]).toContain(res.status);
  });

  test('Hospital → 403', async () => {
    const res = await request(app)
      .post('/api/v1/federation/rounds')
      .set('Authorization', `Bearer ${HOSP_ALPHA()}`)
      .send({ job_id: 'JOB-001', round_id: 'RND-001', round_number: 1 });
    expect(res.status).toBe(403);
  });

  test('Researcher → 403', async () => {
    const res = await request(app)
      .post('/api/v1/federation/rounds')
      .set('Authorization', `Bearer ${RESEARCHER()}`)
      .send({ job_id: 'JOB-001', round_id: 'RND-001', round_number: 1 });
    expect(res.status).toBe(403);
  });
});

// Makes the mocked Python adapter answer the next calls with `payload`.
const adapterReturns = (payload) => {
  const { spawn } = require('child_process');
  const { EventEmitter } = require('events');
  const { Readable } = require('stream');
  spawn.mockImplementation(() => {
    const child = new EventEmitter();
    child.stdout = new Readable({ read() {} });
    child.stderr = new Readable({ read() {} });
    child.stdin = { write: jest.fn((d) => { lastSpawnPayload = JSON.parse(d); }), end: jest.fn() };
    setImmediate(() => { child.stdout.push(JSON.stringify(payload)); child.stdout.push(null); child.emit('close', 0); });
    return child;
  });
};

describe('Round notifications and participant names (Module 18)', () => {
  const Hospital = require('../../src/authentication/models/Hospital');
  const Notification = require('../../src/models/Notification');
  const ROUND = { round_id: 'R1', round_number: 1, federation_job_id: 'JOB1', deadline: '2099-01-01T00:00:00+00:00', expected_participants: ['HOSP-ALPHA'] };

  test('Early aggregation passes force_close and notifies only hospitals that did not join', async () => {
    adapterReturns({ success: true, global_model: { global_model_id: 'GM-1', version: 1 }, round: { ...ROUND, status: 'GLOBAL_MODEL_CREATED' } });
    Hospital.find.mockResolvedValueOnce([{ hospital_id: 'HOSP-BETA' }]);
    const res = await request(app)
      .post('/api/v1/federation/rounds/aggregate')
      .set('Authorization', `Bearer ${ADMIN()}`)
      .send({ job_id: 'JOB1', round_id: 'R1', force_close: true });
    expect(res.status).toBe(200);
    expect(lastSpawnPayload).toMatchObject({ action: 'aggregate', round_id: 'R1', force_close: true });
    expect(Hospital.find.mock.calls[0][0]).toEqual({ status: 'active', hospital_id: { $nin: ['HOSP-ALPHA'] } });
    expect(Notification.insertMany.mock.calls[0][0]).toEqual([
      expect.objectContaining({ hospital_id: 'HOSP-BETA', type: 'ROUND_CLOSED', job_id: 'JOB1', round_id: 'R1' }),
    ]);
    expect(res.body.notified_hospitals).toEqual(['HOSP-BETA']);
  });

  test('Failed aggregation notifies nobody', async () => {
    adapterReturns({ success: false, error: 'Round R1 is not ready for aggregation' });
    const res = await request(app)
      .post('/api/v1/federation/rounds/aggregate')
      .set('Authorization', `Bearer ${ADMIN()}`)
      .send({ job_id: 'JOB1', round_id: 'R1', force_close: true });
    expect(res.status).toBe(500);
    expect(Notification.insertMany).not.toHaveBeenCalled();
  });

  test('Opening a round notifies every active hospital', async () => {
    adapterReturns({ success: true, round: { ...ROUND, expected_participants: [] }, base_model_source: 'seed' });
    Hospital.find.mockResolvedValueOnce([{ hospital_id: 'HOSP-ALPHA' }, { hospital_id: 'HOSP-BETA' }]);
    const res = await request(app)
      .post('/api/v1/federation/rounds')
      .set('Authorization', `Bearer ${ADMIN()}`)
      .send({ job_id: 'JOB1', round_id: 'R1', round_number: 1, deadline: ROUND.deadline });
    expect(res.status).toBe(200);
    expect(res.body.notified_hospitals).toEqual(['HOSP-ALPHA', 'HOSP-BETA']);
    expect(Notification.insertMany.mock.calls[0][0][0]).toMatchObject({ type: 'ROUND_OPEN', round_id: 'R1' });
  });

  test('Admins get participant hospital names with the job list; hospitals do not', async () => {
    adapterReturns({ success: true, jobs: [{ federation_job_id: 'JOB1', rounds: [ROUND] }] });
    Hospital.find.mockResolvedValue([{ hospital_id: 'HOSP-ALPHA', name: 'Alpha General' }]);
    const admin = await request(app).get('/api/v1/federation/jobs').set('Authorization', `Bearer ${ADMIN()}`);
    expect(admin.body.hospital_names).toEqual({ 'HOSP-ALPHA': 'Alpha General' });
    const hosp = await request(app).get('/api/v1/federation/jobs').set('Authorization', `Bearer ${HOSP_BETA()}`);
    expect(hosp.body.hospital_names).toBeUndefined();
    Hospital.find.mockResolvedValue([]);
  });

  test('A hospital reads and clears only its own notifications', async () => {
    const lean = jest.fn().mockResolvedValue([{ notification_id: 'N1', hospital_id: 'HOSP-ALPHA' }]);
    Notification.find.mockReturnValue({ sort: () => ({ limit: () => ({ select: () => ({ lean }) }) }) });
    const res = await request(app).get('/api/v1/notifications').set('Authorization', `Bearer ${HOSP_ALPHA()}`);
    expect(res.status).toBe(200);
    expect(Notification.find).toHaveBeenCalledWith({ hospital_id: 'HOSP-ALPHA' });
    expect(res.body.notifications).toHaveLength(1);

    await request(app).post('/api/v1/notifications/read').set('Authorization', `Bearer ${HOSP_ALPHA()}`);
    expect(Notification.updateMany).toHaveBeenCalledWith({ hospital_id: 'HOSP-ALPHA', read: false }, { read: true });
  });

  test('Researchers and admins have no hospital notifications → 403', async () => {
    for (const token of [RESEARCHER(), ADMIN()]) {
      const res = await request(app).get('/api/v1/notifications').set('Authorization', `Bearer ${token}`);
      expect(res.status).toBe(403);
    }
  });
});

describe('GET /api/v1/federation/rounds/:round_id/base-model/:file', () => {
  const fs = require('fs');
  const os = require('os');
  const path = require('path');
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'm9-base-'));
  fs.writeFileSync(path.join(dir, 'model.safetensors'), 'weights');
  fs.writeFileSync(path.join(dir, 'secret.txt'), 'not served');

  // The adapter answers get_base_model with the checkpoint folder and its two files.
  beforeEach(() => adapterReturns({ success: true, dir, files: ['model.safetensors', 'metadata.json'] }));

  test('Hospital downloads a checkpoint file of the round base model', async () => {
    const res = await request(app)
      .get('/api/v1/federation/rounds/R1/base-model/model.safetensors')
      .set('Authorization', `Bearer ${HOSP_ALPHA()}`)
      .buffer(true).parse((r, cb) => { let d = ''; r.on('data', (c) => { d += c; }); r.on('end', () => cb(null, d)); });
    expect(res.status).toBe(200);
    expect(res.body).toBe('weights');
    expect(lastSpawnPayload).toEqual({ action: 'get_base_model', round_id: 'R1' });
  });

  test('Only the checkpoint files are served', async () => {
    const res = await request(app)
      .get('/api/v1/federation/rounds/R1/base-model/secret.txt')
      .set('Authorization', `Bearer ${HOSP_ALPHA()}`);
    expect(res.status).toBe(404);
  });

  test('Round without a base model → 404', async () => {
    adapterReturns({ success: false, error: 'Round R9 has no base model.' });
    const res = await request(app)
      .get('/api/v1/federation/rounds/R9/base-model/model.safetensors')
      .set('Authorization', `Bearer ${HOSP_ALPHA()}`);
    expect(res.status).toBe(404);
    expect(res.body.error).toMatch(/no base model/);
  });

  test('Researcher → 403', async () => {
    const res = await request(app)
      .get('/api/v1/federation/rounds/R1/base-model/model.safetensors')
      .set('Authorization', `Bearer ${RESEARCHER()}`);
    expect(res.status).toBe(403);
  });
});

// ═════════════════════════════════════════════════════════════════════════════
// SECTION 6 — POST /rounds/aggregate
// ═════════════════════════════════════════════════════════════════════════════

describe('POST /api/v1/federation/rounds/aggregate', () => {
  test('Admin → endpoint reachable', async () => {
    const res = await request(app)
      .post('/api/v1/federation/rounds/aggregate')
      .set('Authorization', `Bearer ${ADMIN()}`)
      .send({ job_id: 'JOB-001', round_id: 'RND-001' });
    expect([200, 500]).toContain(res.status);
  });

  test('Hospital cannot aggregate (403)', async () => {
    const res = await request(app)
      .post('/api/v1/federation/rounds/aggregate')
      .set('Authorization', `Bearer ${HOSP_ALPHA()}`)
      .send({ job_id: 'JOB-001', round_id: 'RND-001' });
    expect(res.status).toBe(403);
  });

  test('Researcher cannot aggregate (403)', async () => {
    const res = await request(app)
      .post('/api/v1/federation/rounds/aggregate')
      .set('Authorization', `Bearer ${RESEARCHER()}`)
      .send({ job_id: 'JOB-001', round_id: 'RND-001' });
    expect(res.status).toBe(403);
  });
});

// ═════════════════════════════════════════════════════════════════════════════
// SECTION 7 — GET /models
// ═════════════════════════════════════════════════════════════════════════════

describe('GET /api/v1/federation/models', () => {
  test('Admin → 200 + models array', async () => {
    const res = await request(app)
      .get('/api/v1/federation/models')
      .set('Authorization', `Bearer ${ADMIN()}`);
    expect(res.status).toBe(200);
    expect(res.body.success).toBe(true);
    expect(Array.isArray(res.body.models)).toBe(true);
  });

  test('Hospital Alpha cannot access global model list (403)', async () => {
    const res = await request(app)
      .get('/api/v1/federation/models')
      .set('Authorization', `Bearer ${HOSP_ALPHA()}`);
    expect(res.status).toBe(403);
  });

  test('Hospital Beta cannot access global model list (403)', async () => {
    const res = await request(app)
      .get('/api/v1/federation/models')
      .set('Authorization', `Bearer ${HOSP_BETA()}`);
    expect(res.status).toBe(403);
  });

  test('Researcher cannot access global model list (403)', async () => {
    const res = await request(app)
      .get('/api/v1/federation/models')
      .set('Authorization', `Bearer ${RESEARCHER()}`);
    expect(res.status).toBe(403);
  });

  test('Unauthenticated → 401', async () => {
    const res = await request(app).get('/api/v1/federation/models');
    expect(res.status).toBe(401);
  });
});

// ═════════════════════════════════════════════════════════════════════════════
// SECTION 8 — POST /models/evaluate
// ═════════════════════════════════════════════════════════════════════════════

describe('POST /api/v1/federation/models/evaluate', () => {
  test('Admin → endpoint reachable', async () => {
    const res = await request(app)
      .post('/api/v1/federation/models/evaluate')
      .set('Authorization', `Bearer ${ADMIN()}`)
      .send({ global_model_id: 'GM-001' });
    expect([200, 500]).toContain(res.status);
  });

  test('Hospital cannot trigger evaluation (403)', async () => {
    const res = await request(app)
      .post('/api/v1/federation/models/evaluate')
      .set('Authorization', `Bearer ${HOSP_ALPHA()}`)
      .send({ global_model_id: 'GM-001' });
    expect(res.status).toBe(403);
  });

  test('Researcher cannot trigger evaluation (403)', async () => {
    const res = await request(app)
      .post('/api/v1/federation/models/evaluate')
      .set('Authorization', `Bearer ${RESEARCHER()}`)
      .send({ global_model_id: 'GM-001' });
    expect(res.status).toBe(403);
  });
});

// ═════════════════════════════════════════════════════════════════════════════
// SECTION 9 — POST /models/promote
// ═════════════════════════════════════════════════════════════════════════════

describe('POST /api/v1/federation/models/promote', () => {
  test('Admin → endpoint reachable', async () => {
    const res = await request(app)
      .post('/api/v1/federation/models/promote')
      .set('Authorization', `Bearer ${ADMIN()}`)
      .send({ global_model_id: 'GM-001', eval_record_id: 'EVAL-001' });
    expect([200, 500]).toContain(res.status);
  });

  test('Hospital cannot trigger promotion (403)', async () => {
    const res = await request(app)
      .post('/api/v1/federation/models/promote')
      .set('Authorization', `Bearer ${HOSP_ALPHA()}`)
      .send({ global_model_id: 'GM-001', eval_record_id: 'EVAL-001' });
    expect(res.status).toBe(403);
  });

  test('Researcher cannot trigger promotion (403)', async () => {
    const res = await request(app)
      .post('/api/v1/federation/models/promote')
      .set('Authorization', `Bearer ${RESEARCHER()}`)
      .send({ global_model_id: 'GM-001', eval_record_id: 'EVAL-001' });
    expect(res.status).toBe(403);
  });
});

// ═════════════════════════════════════════════════════════════════════════════
// SECTION 10 — GET /hospital-status (extended)
// ═════════════════════════════════════════════════════════════════════════════

describe('GET /api/v1/federation/hospital-status', () => {
  test('Hospital Alpha → 200 + updates array', async () => {
    const res = await request(app)
      .get('/api/v1/federation/hospital-status')
      .set('Authorization', `Bearer ${HOSP_ALPHA()}`);
    expect(res.status).toBe(200);
    expect(res.body.success).toBe(true);
    expect(Array.isArray(res.body.updates)).toBe(true);
  });

  test('Hospital Beta → 200 + updates array', async () => {
    const res = await request(app)
      .get('/api/v1/federation/hospital-status')
      .set('Authorization', `Bearer ${HOSP_BETA()}`);
    expect(res.status).toBe(200);
    expect(res.body.success).toBe(true);
    expect(Array.isArray(res.body.updates)).toBe(true);
  });

  test('Hospital A cannot access Hospital B status — different hospital_ids reach M9', async () => {
    // Hospital A's token cannot produce Hospital B's hospital_id
    // The authMiddleware fetches the User record from DB — it cannot be spoofed
    // even if the JWT itself claimed a different hospital_id
    const res = await request(app)
      .get('/api/v1/federation/hospital-status')
      .set('Authorization', `Bearer ${HOSP_ALPHA()}`);
    expect(res.status).toBe(200);
    // M9 receives ONLY HOSP-ALPHA, not HOSP-BETA
    expect(lastSpawnPayload.hospital_id).toBe('HOSP-ALPHA');
    expect(lastSpawnPayload.hospital_id).not.toBe('HOSP-BETA');
  });

  test('Unauthenticated → 401', async () => {
    const res = await request(app).get('/api/v1/federation/hospital-status');
    expect(res.status).toBe(401);
  });

  test('Admin cannot access hospital-status (403) — role guard before hospital_id check', async () => {
    const res = await request(app)
      .get('/api/v1/federation/hospital-status')
      .set('Authorization', `Bearer ${ADMIN()}`);
    expect(res.status).toBe(403);
  });

  test('Researcher cannot access hospital-status (403)', async () => {
    const res = await request(app)
      .get('/api/v1/federation/hospital-status')
      .set('Authorization', `Bearer ${RESEARCHER()}`);
    expect(res.status).toBe(403);
  });
});

// ═════════════════════════════════════════════════════════════════════════════
// SECTION 11 — SECURITY: JWT validation and server-side enforcement
// ═════════════════════════════════════════════════════════════════════════════

describe('Security — JWT validation and server-side enforcement', () => {
  test('Malformed JWT rejected (401)', async () => {
    const res = await request(app)
      .get('/api/v1/federation/jobs')
      .set('Authorization', 'Bearer this.is.not.valid');
    expect(res.status).toBe(401);
  });

  test('Expired JWT rejected (401)', async () => {
    const expired = jwt.sign(
      { sub: 'USR_adm0001', user_id: 'USR_adm0001', role: 'admin', hospital_id: null },
      JWT_SECRET,
      { expiresIn: '-1s' }
    );
    const res = await request(app)
      .get('/api/v1/federation/jobs')
      .set('Authorization', `Bearer ${expired}`);
    expect(res.status).toBe(401);
  });

  test('No Authorization header → 401', async () => {
    const res = await request(app).get('/api/v1/federation/models');
    expect(res.status).toBe(401);
  });

  test('Hospital cannot access global model weights (403) — server-side, not frontend hiding', async () => {
    // This test is a direct HTTP call — it bypasses any frontend entirely
    // The 403 comes from requireRole(ROLES.ADMIN) middleware on the server
    const res = await request(app)
      .get('/api/v1/federation/models')
      .set('Authorization', `Bearer ${HOSP_ALPHA()}`);
    expect(res.status).toBe(403);
    // And Python subprocess was NOT called
    expect(lastSpawnPayload).toBeNull();
  });

  test('Researcher aggregation attempt blocked server-side (403)', async () => {
    const res = await request(app)
      .post('/api/v1/federation/rounds/aggregate')
      .set('Authorization', `Bearer ${RESEARCHER()}`)
      .send({ job_id: 'JOB-001', round_id: 'RND-001' });
    expect(res.status).toBe(403);
    // Python subprocess was NOT called — middleware blocked first
    expect(lastSpawnPayload).toBeNull();
  });

  test('Hospital cannot trigger evaluation server-side (403)', async () => {
    const res = await request(app)
      .post('/api/v1/federation/models/evaluate')
      .set('Authorization', `Bearer ${HOSP_BETA()}`)
      .send({ global_model_id: 'GM-001' });
    expect(res.status).toBe(403);
    expect(lastSpawnPayload).toBeNull();
  });

  test('Hospital cannot create federation rounds server-side (403)', async () => {
    const res = await request(app)
      .post('/api/v1/federation/rounds')
      .set('Authorization', `Bearer ${HOSP_ALPHA()}`)
      .send({ job_id: 'JOB-001', round_id: 'RND-001', round_number: 1 });
    expect(res.status).toBe(403);
    expect(lastSpawnPayload).toBeNull();
  });

  test('Researcher cannot promote global models server-side (403)', async () => {
    const res = await request(app)
      .post('/api/v1/federation/models/promote')
      .set('Authorization', `Bearer ${RESEARCHER()}`)
      .send({ global_model_id: 'GM-001', eval_record_id: 'EVAL-001' });
    expect(res.status).toBe(403);
    expect(lastSpawnPayload).toBeNull();
  });

  test('Admin remains able to perform federation administration', async () => {
    const jobs = await request(app)
      .get('/api/v1/federation/jobs')
      .set('Authorization', `Bearer ${ADMIN()}`);
    const models = await request(app)
      .get('/api/v1/federation/models')
      .set('Authorization', `Bearer ${ADMIN()}`);
    expect(jobs.status).toBe(200);
    expect(models.status).toBe(200);
  });
});

// ═════════════════════════════════════════════════════════════════════════════
// SECTION 12 — DELETION
// ═════════════════════════════════════════════════════════════════════════════

describe('DELETE /api/v1/federation/jobs/:job_id', () => {
  test('Admin → endpoint reachable (200/500)', async () => {
    const res = await request(app)
      .delete('/api/v1/federation/jobs/JOB-001')
      .set('Authorization', `Bearer ${ADMIN()}`);
    expect([200, 500]).toContain(res.status);
  });
  test('Unauthenticated → 401', async () => {
    const res = await request(app).delete('/api/v1/federation/jobs/JOB-001');
    expect(res.status).toBe(401);
  });
  test('Hospital → 403', async () => {
    const res = await request(app)
      .delete('/api/v1/federation/jobs/JOB-001')
      .set('Authorization', `Bearer ${HOSP_ALPHA()}`);
    expect(res.status).toBe(403);
  });
  test('Researcher → 403', async () => {
    const res = await request(app)
      .delete('/api/v1/federation/jobs/JOB-001')
      .set('Authorization', `Bearer ${RESEARCHER()}`);
    expect(res.status).toBe(403);
  });
});

describe('DELETE /api/v1/federation/rounds/:round_id', () => {
  test('Admin → endpoint reachable (200/500)', async () => {
    const res = await request(app)
      .delete('/api/v1/federation/rounds/RND-001')
      .set('Authorization', `Bearer ${ADMIN()}`);
    expect([200, 500]).toContain(res.status);
  });
  test('Unauthenticated → 401', async () => {
    const res = await request(app).delete('/api/v1/federation/rounds/RND-001');
    expect(res.status).toBe(401);
  });
  test('Hospital → 403', async () => {
    const res = await request(app)
      .delete('/api/v1/federation/rounds/RND-001')
      .set('Authorization', `Bearer ${HOSP_ALPHA()}`);
    expect(res.status).toBe(403);
  });
  test('Researcher → 403', async () => {
    const res = await request(app)
      .delete('/api/v1/federation/rounds/RND-001')
      .set('Authorization', `Bearer ${RESEARCHER()}`);
    expect(res.status).toBe(403);
  });
});

// ═════════════════════════════════════════════════════════════════════════════
// GET /api/v1/federation/models — Global Model listing
//
// Verifies:
//   1. Returns HTTP 200 with valid JSON when models exist
//   2. Returns valid JSON empty collection when no models
//   3. No JSON parsing exception on existing model
//   4. Provenance fields survive serialization
//   5. R3 global model remains unchanged (not recreated)
//   6. Admin authorization is required
// ═════════════════════════════════════════════════════════════════════════════

describe('GET /api/v1/federation/models — Global Model listing', () => {
  // Helper: arm spawn to return a specific Python adapter response
  function armSpawn(responseObj) {
    const { spawn } = require('child_process');
    const { EventEmitter } = require('events');
    const { Readable } = require('stream');
    spawn.mockImplementationOnce(() => {
      const child = new EventEmitter();
      child.stdout = new Readable({ read() {} });
      child.stderr = new Readable({ read() {} });
      child.stdin = { write: jest.fn(), end: jest.fn() };
      setImmediate(() => {
        child.stdout.push(JSON.stringify(responseObj));
        child.stdout.push(null);
        child.emit('close', 0);
      });
      return child;
    });
  }

  // Canonical R3 global model fixture (matches the real DB record)
  const GM_R3 = {
    global_model_id: 'GM-MALARIA-MOBILENET_V3_SMALL-V1',
    task: 'Malaria',
    task_type: 'image_classification',
    architecture: 'mobilenet_v3_small',
    version: 1,
    status: 'EVALUATION_PENDING',
    created_at: '2026-10-07T20:23:57.722730+00:00',
    class_mapping: { Parasitized: 0, Uninfected: 1 },
    schema_hash: '748826f528c7a83e72c41b8498e5f4ed2b411ea8f16632aa14bf8aaae86858f5',
    federation_job_id: 'JOB_MAL_MNV3S_CANONICAL_E2E_3',
    round_id: 'ROUND_MAL_MNV3S_CANONICAL_E2E_R3',
    source_update_ids: ['UPD-4D31F500', 'UPD-0457B695'],
    aggregation_method: 'weighted_fedavg',
    aggregation_metadata: { total_samples: 44092, non_float_policy: 'first_participant' },
    artifact_checksum: 'f8046529619e7446fa7c9297114efd423efb7d4f9ac972f6f5caa98bdba81b2c',
    evaluations: [],
  };

  test('1. With one existing Global Model → HTTP 200 and valid JSON containing the model', async () => {
    armSpawn({ success: true, models: [GM_R3] });
    const res = await request(app)
      .get('/api/v1/federation/models')
      .set('Authorization', `Bearer ${ADMIN()}`);

    expect(res.status).toBe(200);
    // Must be parseable JSON (not empty/non-JSON body)
    expect(() => JSON.parse(res.text)).not.toThrow();
    const body = JSON.parse(res.text);
    expect(body.success).toBe(true);
    expect(Array.isArray(body.models)).toBe(true);
    expect(body.models.length).toBeGreaterThanOrEqual(1);
    const gm = body.models.find(m => m.global_model_id === 'GM-MALARIA-MOBILENET_V3_SMALL-V1');
    expect(gm).toBeDefined();
  });

  test('2. With zero models → HTTP 200 and valid empty JSON collection', async () => {
    armSpawn({ success: true, models: [] });
    const res = await request(app)
      .get('/api/v1/federation/models')
      .set('Authorization', `Bearer ${ADMIN()}`);

    expect(res.status).toBe(200);
    expect(() => JSON.parse(res.text)).not.toThrow();
    const body = JSON.parse(res.text);
    expect(body.success).toBe(true);
    expect(Array.isArray(body.models)).toBe(true);
    expect(body.models.length).toBe(0);
  });

  test('3. Existing Global Model serializes without JSON parsing exception', async () => {
    armSpawn({ success: true, models: [GM_R3] });
    const res = await request(app)
      .get('/api/v1/federation/models')
      .set('Authorization', `Bearer ${ADMIN()}`);

    // Must be HTTP 200 — NOT 500
    expect(res.status).toBe(200);
    expect(res.text).toBeTruthy();
    // Must not be the "Expecting value" JSON parse error
    expect(res.text).not.toContain('Expecting value');
    // Must be parseable
    expect(() => JSON.parse(res.text)).not.toThrow();
  });

  test('4. GM_R3 provenance fields survive serialization', async () => {
    armSpawn({ success: true, models: [GM_R3] });
    const res = await request(app)
      .get('/api/v1/federation/models')
      .set('Authorization', `Bearer ${ADMIN()}`);

    expect(res.status).toBe(200);
    const body = JSON.parse(res.text);
    const gm = body.models.find(m => m.global_model_id === 'GM-MALARIA-MOBILENET_V3_SMALL-V1');
    expect(gm).toBeDefined();

    // Provenance fields
    expect(gm.round_id).toBe('ROUND_MAL_MNV3S_CANONICAL_E2E_R3');
    expect(gm.federation_job_id).toBe('JOB_MAL_MNV3S_CANONICAL_E2E_3');
    expect(gm.source_update_ids).toEqual(expect.arrayContaining(['UPD-4D31F500', 'UPD-0457B695']));
    expect(gm.task).toBe('Malaria');
    expect(gm.architecture).toBe('mobilenet_v3_small');

    // class_mapping must be an object, not a string
    expect(typeof gm.class_mapping).toBe('object');
    expect(gm.class_mapping).not.toBeNull();
    expect(gm.class_mapping.Parasitized).toBe(0);
    expect(gm.class_mapping.Uninfected).toBe(1);

    // status must be the model status, not the class_mapping JSON
    expect(gm.status).toBe('EVALUATION_PENDING');
    expect(gm.status).not.toContain('Parasitized');

    // created_at must be the timestamp, not the schema_hash
    expect(gm.created_at).toMatch(/^\d{4}-\d{2}-\d{2}T/);
  });

  test('5. R3 Global Model ID is unchanged — not recreated by listing', async () => {
    // Call the listing endpoint twice; the model ID must remain the same
    armSpawn({ success: true, models: [GM_R3] });
    const res1 = await request(app)
      .get('/api/v1/federation/models')
      .set('Authorization', `Bearer ${ADMIN()}`);
    armSpawn({ success: true, models: [GM_R3] });
    const res2 = await request(app)
      .get('/api/v1/federation/models')
      .set('Authorization', `Bearer ${ADMIN()}`);

    expect(res1.status).toBe(200);
    expect(res2.status).toBe(200);

    const body1 = JSON.parse(res1.text);
    const body2 = JSON.parse(res2.text);

    const gm1 = body1.models.find(m => m.global_model_id === 'GM-MALARIA-MOBILENET_V3_SMALL-V1');
    const gm2 = body2.models.find(m => m.global_model_id === 'GM-MALARIA-MOBILENET_V3_SMALL-V1');

    expect(gm1).toBeDefined();
    expect(gm2).toBeDefined();
    // Model identity must be stable across calls
    expect(gm1.global_model_id).toBe(gm2.global_model_id);
    expect(gm1.artifact_checksum).toBe(gm2.artifact_checksum);
    expect(gm1.aggregation_method).toBe(gm2.aggregation_method);
  });

  test('6. Admin authorization required — unauthenticated → 401, hospital → 403, researcher → 403', async () => {
    const unauth = await request(app).get('/api/v1/federation/models');
    expect(unauth.status).toBe(401);

    const hosp = await request(app)
      .get('/api/v1/federation/models')
      .set('Authorization', `Bearer ${HOSP_ALPHA()}`);
    expect(hosp.status).toBe(403);

    const researcher = await request(app)
      .get('/api/v1/federation/models')
      .set('Authorization', `Bearer ${RESEARCHER()}`);
    expect(researcher.status).toBe(403);
  });
});

